### ISSUE TITLE
New Product using Iro!

### ISSUE THREAD

**Issue by rwwagner90** [jaames/iro.js#104]
@jaames I know a GitHub issue isn't the best place for this, so feel free to close, but I wanted to let you know we're launching the beta of Swach today, which uses Iro!

Please check it out and share with your friends and colleagues and let us know your thoughts!

https://www.producthunt.com/posts/swach

We're so appreciative of all the work you have done on Iro, and this product would not have been possible without you 😃.

**Comment by jaames** [comment]
Hey @rwwagner90! It's super cool to see what you've done with iro! I actually downloaded Swach a couple of days back and so far it's been a really solid little app, definitely gonna use it in my day-to-day :)

**Comment by rwwagner90** [comment]
@jaames I'm so glad to hear that! We would really appreciate it if you shared Swach with your friends and colleagues! Also, if you have any ideas on new features or feedback on the app, please let us know. We're working on building out the next set of features now.

**Comment by jaames** [comment]
@rwwagner90 Yeah, sure thing! 

Feedback-wise I feel as though some UI flows are a tad convoluted, for example it took me a while to figure out how to edit the colors in a palette since I was originally clicking on the color swatches - I didn't realise that you had to click on the `...` icon instead. Making it easier to get to the contrast checker would also be nice, perhaps by adding an extra icon for it next to the eyedropper and color picker ones? I really dig the look of UI overall though, especially dark mode 😎

If I could request any features: custom global key shortcuts for activating the eyedropper / contrast checker / color picker modes would be rad, also the ability to use the eyedropper anywhere you can pick a color would be very handy for e.g. quickly using the contrast checker to test contrast between two colors on-screen. If both of these were implemented then Swach would pretty much replace [Contrast](https://usecontrast.com/) for me!

By the way - I would totally recommend submitting Swach to [Codrops Collective](https://tympanus.net/codrops/submit/) when you think it's ready. Iro.js really took off when I submitted it there a while back

Of course do let me know if there's anything else that I can add to iro.js too, the UK just went into full COVID-19 lockdown so I guess I have plenty of free time now :^)

**Comment by rwwagner90** [comment]
@jaames thanks for the feedback! I definitely think those are good ideas. Will work on integrating some of them over the next couple weeks.

> By the way - I would totally recommend submitting Swach to Codrops Collective when you think it's ready. Iro.js really took off when I submitted it there a while back

Does stuff submitted there have to be open source?

**Comment by jaames** [comment]
@rwwagner90 Great! I look forward to seeing them :)

> Does stuff submitted there have to be open source?

I don't think so, as far as I'm aware Codrops will accept anything so long as it's somewhat related to web dev / design

**Comment by rwwagner90** [comment]
@jaames 
> custom global key shortcuts for activating the eyedropper / contrast checker / color picker modes would be rad

Are you saying you would like to be able to set which keys activate these things or just that some way to activate via keyboard exists?

**Comment by jaames** [comment]
A bit of both I guess, basically multiple key combos that open the app, but each one opens it in a different mode, like color picker / contrast checker / etc

**Comment by rwwagner90** [comment]
@jaames but are you saying the user needs to be able to choose the key combination or does that not matter as long as there is one that can be used?

**Comment by jaames** [comment]
@rwwagner90 it doesnt matter, but it would be nice if they could!

**Comment by rwwagner90** [comment]
@jaames I just added a keyboard shortcut for opening the contrast checker, as well as allowing right clicking the menu bar icon to bring up the option as well. Also, I added eyedropper support to the color inputs for the contrast checker. Still working on incorporating all your feedback, but let me know how those things work for you! If you are on MacOS or Windows, I believe the app should auto update for you.
