### ISSUE TITLE
Is it possible to change layout direction when the window is resized?

### ISSUE THREAD

**Issue by scottyeung** [jaames/iro.js#120]
I'm using iro.js in React. Currently when width is changed I would have to reinitialise the ref, as there's no event available to change the layoutDirection via the API. Is that something you would consider to bring up in future? Or there's a workaround for the problem?

At last, thanks for the awesome work, James!

**Comment by jaames** [comment]
Kinda! You can update any option whenever you like with `colorPicker.setState()`, but looks like I forgot to document this... sorry about that. Since you're using React it's probably pretty familiar to you, e.g.

```js
colorPicker.setState({ layoutDirection: 'vertical' });
```

Currently the logic to do that on window resize is left up to you, but I reckon that ought to be added as a feature somehow

And thank you for the kind words!

**Comment by scottyeung** [comment]
Works like a charm! Thanks!
