### ISSUE TITLE
min/max value options for all slider types

### ISSUE THREAD

**Issue by Mjinx** [jaames/iro.js#125]
It would be nice to change temp range to min and max so it could be applied to other types of sliders such as Alpha.  

or is there other ways to limit the alpha range that is reflected on the slider itself (rather than clamping the value on change event)

**Comment by jaames** [comment]
Hi! 

It would be really appreciated if you could provide some potential use-cases for this, I'm struggling to think of any situations where changing the range of the other sliders would be particularly useful or intuitive for users?

In theory it wouldn't be too hard to add, but I prefer not adding extra features unless they're actually going to be helpful, otherwise they're just bloat :)

**Comment by Mjinx** [comment]
You got me at the bloat and yeah my edge use case might be fairly unique and specific to my use of alpha, not too sure if any one would use the limits for other color channels...

Looking at the API options if there's a Kelvin specific limits a more generic might be available or might be handy.

As for my use case, I have highlighted annotations where ideally I want to prevent users to set alpha value to 0 or 1 as I require some transparency (being an highlight and all)

I tried to use slider input but it didn't look right and wasn't too sure about the custom iro components.

That said, thanks for the great work you done here 👍
