### ISSUE TITLE
Iro.js in nuxt

### ISSUE THREAD

**Issue by raldone01** [jaames/iro.js#131]
When I try to use iro in nuxt it fails because document is undefined.
It fails on [this line](https://github.com/jaames/iro.js/blob/eaf701c9a9e550a0c196a2f3d4413be54284e334/dist/iro.js#L1035).
If I manually set BASE_ELEMENTS to {} it seems to work on windows firefox. BASE_ELEMENTS seems to be necessary for safari only. It would be awesome to fix this issue to enable server side rendering.
I searched for it with this [query](https://github.com/jaames/iro.js/search?q=BASE_ELEMENTS&unscoped_q=BASE_ELEMENTS). It seems to originate from rollup because BASE_ELEMENTS is not defined in the code.

**Comment by jaames** [comment]
Ah, this is likely happening when Nuxt does its server-side page render, since DOM objects like `document` aren't defined in that environment. 

Nuxt's guide has a workaround for client-side libraries that aren't compatible with this: https://nuxtjs.org/examples/plugins -- I think the general idea is you need to require the library only when `process.client` is true and do all the library setup in the component's `mounted()` method, since that only gets called on the client-side. Let me know if you need some sample code for that :)

P.S. the culprit line is actually from iro-core: https://github.com/irojs/iro-core/blob/typescript/src/util.ts, but I don't think it's possible to make this compatible with SSR environments without reintroducing more rendering bugs in Safari

**Comment by raldone01** [comment]
Thank you for your reply. 
It would be fixed by initializing the base variable to undefined and then assigning it in the function once if the performance overhead is that bad. If the performance overhead of `document.getElementsByTagName('base')` is not relevant it may be possible to remove the global variable and just use that code directly in the if or initialize the variable every time in the function itself.
I would like to use iro.Color while server side rendering the site. This also prevents me from importing iro just for the types.
As this is the only issue when server side rendering it should be an easy fix. Please think about it.

**Comment by jaames** [comment]
Just pushed changes and published iro.js v5.2.3 on npm to fix this - thanks @raldone01!

**Comment by hmaesta** [comment]
Hey, @raldone01.
Did you wrapped **iro.js** into a **Vue** plugin and mapped all events? Would you mind posting your setup as open-source?

[irojs/vue-iro-color-picker](https://github.com/irojs/vue-iro-color-picker) is the only Vue wrapper I found, but it looks very outdated (3.5.6 vs current 5.1.0).

Really appreciate.

**Comment by raldone01** [comment]
@hmaesta I didn't write a proper vue wrapper and I unfortunately don't have time to do so. I only wrote one to fit my specific use case.
