### ISSUE TITLE
picker is not working in firefox as exected

### ISSUE THREAD

**Issue by Christian-Me** [jaames/iro.js#186]
This relates to https://github.com/jaames/iro.js/issues/185#issuecomment-828567753

Updated to latest version (78.10.0 32bit) but still no color drawn: 
![image](https://user-images.githubusercontent.com/15779507/116437762-0c2b1e80-a84e-11eb-9cc1-2ff93ed7fc76.png)

**Comment by Christian-Me** [comment]
No issue in the latest 64bit version 88.0! Don't know why firefox installs the 32bit version automatically.  So no worries - time will solve that problem
Can be closed if you don't want to dig deeper here 
![image](https://user-images.githubusercontent.com/15779507/116439383-c53e2880-a84f-11eb-94e0-701537e8e32e.png)

**Comment by jaames** [comment]
Version 78 is pretty out of date isn't it? The latest major version of Firefox is 88, conical gradient support was added in 83, which is why the color picker isn't being rendered correctly.

If you aren't able to update to any new version, as of version 75 you can enable `layout.css.conic-gradient.enabled` in `about:config`. You could also try a conic gradient polyfill: https://projects.verou.me/conic-gradient/

**Comment by jaames** [comment]
Oop, didn't see your update while I was typing that. Glad you got things sorted :)
