### ISSUE TITLE
Saturation gradient isn't being rendered correctly on Android

### ISSUE THREAD

**Issue by Sind** [jaames/iro.js#2]
![screenshot_iro](https://cloud.githubusercontent.com/assets/2745906/24674203/f10d7460-197a-11e7-811a-37bb60cd33ee.png)

Using Chromium on Android (Also looks the same in FireFox)

Strangely enough, the picked color is correct(what color _should_ be at that location on the wheel).

**Comment by jaames** [comment]
Now that's certainly a strange one. Thank you for the report!

It looks like the hue ring is fine, but the radial gradient used to represent saturation isn't being drawn correctly, which pretty much narrows down the issue to these lines of code: https://github.com/jaames/iro.js/blob/master/src/iro.js#L557:L561.

I've recreated the bug in a codepen here:
http://codepen.io/rakujira/pen/rybVXW?editors=1011

I don't personally have an Android device to test with (hence why it managed slipped past me in the first place), however a friend was able to confirm that this is an issue on their device too. 

If I'm honest here, I'm pretty sure that this is an Android bug since I'm not be doing anything out of the ordinary as far as I can tell. I'll be sure to do more testing first, though.

--

Oh, and yeah, as you noted this won't present any change with the picked color. That's calculated based on the position of the markers. (:

**Comment by Sind** [comment]
I have only tested this in Android so far, but changing the "2" to "0" seems to fix the issue.

**Comment by Sind** [comment]
And yea. Seems like createRadialGradient on Android struggles with radiuses between 0 and 15. Strange =/

**Comment by jaames** [comment]
That's... certainly odd. Oh well, at least we know what's causing it ¯\_(ツ)_/¯

I've committed a hotfix for the issue which implements the changes that you suggested, I hope it's resolved now

Thanks again!

**Comment by Sind** [comment]
Looks good. I'll close this issue then.

Btw, it's good practice to close an issue when you think you've fixed it, and leave it to the other users to re-open it if there's more.

Also, no problem. I've been looking for a lightweight colorpicker widget, and this looks perfect!(All the other nice looking ones require jQuery, bleh)

**Comment by jaames** [comment]
I see, thanks for the tip!

I hope you find it useful for your needs. By the way, I'm currently rewriting everything from the ground up over in the v2 branch, so please feel free to open up another issue if you have any feature requests or anything. It would be helpful to get some feedback. (:
