### ISSUE TITLE
Color Picker Box - slightly inaccurate Colors

### ISSUE THREAD

**Issue by Awendel** [jaames/iro.js#233]
The Box, which is based on HSB Colors, is slightly inaccurate, especially towards the top left.

The reason being that it is implemented with stacked linear gradients and not a true shader that computes the color of a pixel based on position.

One can easily validate this, by using the new Eyedropper API. When clicking on a point on the box with the Eyedropper and syncing the selected Color with Iro, it should technically put the circle exactly where you clicked, yet there is quite a strong shift down left, especially with colors with higher saturation.

Henceforth I suggest changing the Code for generating the Box Gradients using a GLSL shader.

Using the normal Canvas API will probably create too much latency when using the .getImageData / .putImageData approach. So WebGL is the only option.

This might also decrease a current issue with banding, because stacked linear gradients interefere with the the dithering values of each other. If one was to use a GLSL gradient, that wouldn't be an issue and the optics would be much improved.

If this is too much of a coding challenge, I'm sure there is some other open source JS projects that have already the code for rendering the shader, since it's quite a commonly used algorithm.

**Comment by jaames** [comment]
My plan going forward is to use plain CSS+HTML/SVG for as much as possible for a few reasons:
1) I want all components to be resizable with just CSS so that the color picker can be fully responsive, ideally without having to use anything like resize observers
2) HTML makes it easy for people to style the library as they wish
3) I want to keep the bundle size as low as possible

Personally I don't really see a slight inaccuracy being much of an issue so long as end-users of the color picker can understand the effect of moving a color handle in a certain direction. The color is already calculated using math based on the position of the handles, I don't think it's a big enough issue to warrant messing around with webgl and shaders.
