### ISSUE TITLE
circle selector barely visible

### ISSUE THREAD

**Issue by rshensley** [jaames/iro.js#239]
For some reason the circle selector for the color wheel and slider are barely visible with default settings being used and nothing being modified. Is there anything I should look for to resolve this?

**Comment by jaames** [comment]
Obviously I can only make vague guesses without a screenshot, but the first thing to check would be the [codepen example](https://codepen.io/rakujira/pen/WZOeNq) to see if you get a similar issue there as well, which would rule out any browser weirdness.

If the codepen demo works as expected then you probably have some CSS styles being applied to all `svg` elements, since the handles are SVGs that would be an issue.
