### ISSUE TITLE
Prevent color:change from immediately firing its callback

### ISSUE THREAD

**Issue by jbellue** [jaames/iro.js#60]
In [issue #59](https://github.com/jaames/iro.js/issues/59) you mention that the color:change event fires intentionally: 
> It's worth noting that color:update also (intentionally) fires once with the initial color value too

To me, this isn't straightforward.
I'm trying to prevent firing the event when programmatically setting the color, so I tried to first remove the callback, set the color, and add the callback, but then it fires again:
```
colorPicker.off("color:change", colorChangeCallback);
colorPicker.color.set("#00FF00");
colorPicker.on("color:change", colorChangeCallback);
```

I think the most obvious solution would be to not fire the event when adding the callback, but having a way to set the color with an extra boolean to trigger (or not) the event would also suit me (I think v3 had that at some point ?, like `colorPicker.color.set("#00FF00", false);`)

Tell me if I'm missing something obvious.

BTW, thanks for the awesome project!

**Comment by jaames** [comment]
Hey @jbellue!

If you just want to catch when the color has changed with user input, there are input events (`input:start`, `input:move` and `input:end`) that might be more suitable? 

Passing `false` as a second parameter to `color.set` was only ever a temporary hack to prevent infinite callback loops if you tried setting the color within a `color:update` callback. It was never really an ideal solution because it didn't work with any of the color properties (`color.rgbString`, etc) so when I found a much better way to prevent that issue internally I removed that parameter altogether.

`color:change` fires when you add the callback is because I thought it made sense to call it once with the initial value that you pass to the wheel, althouuugh I didn't really anticipate that people would have any reason to remove the callback and then add it again. I can see why that might catch someone out -- I think I'll probably change this behaviour and have a seperate `color:init` event or something. 

On that same train of thought, I might also add an `input:change` event which is the same as `color:change` but only fires with user input.

**Comment by jbellue** [comment]
Using both `input:move` and `input:end` work for me, true.
I reckon that's essentially what `input:change` would do.

To me, it makes more sense to not fire when you add the `color:change` callback, but I guess always triggering it when the color changes seems logical (both on `set` and `input`).

I think the `input` callbacks are the right solution, but the `input:move` isn't documented (and had a typo, I submitted [pull #61 ](https://github.com/jaames/iro.js/pull/61))

**Comment by jaames** [comment]
Currently working on adding `input:change` over in the events-api-update branch if you'd like to take a look! Right now it's fired in the colorPicker's updateColor method, just before the `color:change` event. It has the same parameters and loop protection as `color:change` too.

Yeah, I think my logic was that it should *always* fire when the color changes, including when the initial color is set. I'm going to go ahead and remove that behaviour and replace it with a 'color:init', which again has the same parameters as `color:change` because it's still a helpful thing to have. 

Thanks for the contribution btw! I'll make sure to document the events better after this change is done.

**Comment by jaames** [comment]
Just pushed [v4.3.0](https://github.com/jaames/iro.js/blob/master/CHANGELOG.md#430)! You can now use `input:change` to achieve what you need, plus there's a couple of other new additions.
