### ISSUE TITLE
Suggestion: Wheel Lightness Step 0 is hexString=#000000 flag that change Step 0 to Step 1

### ISSUE THREAD

**Issue by creppu** [jaames/iro.js#65]
I use iro.js to control my lights.
At night I want the lowest brightness available for the color.
At step 0, the light goes out and I always try to touch step 1 to reach it.
Maybe a flag would be nice to change the behavior on step 0.
Off, or the lowest possible brightness.

![sliderStep0](https://user-images.githubusercontent.com/33027885/56219820-abb25580-6067-11e9-967c-e8a9984a8168.png)

**Comment by jaames** [comment]
You'd like to limit the color's brightness so that it never reaches 0? 

The easiest way to do this is by using the color picker's `color:change` event to update the color if the brightness falls below 1:

```js
colorPicker.on("color:change", function(color) {
  var hsv = color.hsv;
  // don't allow the color's brightness to be smaller than 1
  if (hsv.v < 1) {
    color.hsv = { h: hsv.h, s: hsv.s, v:1 }
  }
}
```

I'd prefer not to add a built-in option/flag for this, since the use-case is quite niche and it would only add more bloat and potential for bugs. 

Hope that snippet helps, though :)
