### ISSUE TITLE
Drawing the wheel always with full brightness

### ISSUE THREAD

**Issue by Ape** [jaames/iro.js#9]
I'd like to have an option for always drawing the wheel with full brightness (V channel = 100%) regardless of the slider value.

**Comment by jaames** [comment]
Thank you for the suggestion! 

So if I understand correctly, the idea is to optionally hide the value/brightness slider completely and just have the hue wheel? It seems reasonable, there's a couple of things I'd like to ask, though:

* Any preference regarding the name of the "disable the brightness slider" option? I feel like setting `valueSlider: false` makes sense, but I'm open to suggestions.
* How should the color picker behave when the color is set via JavaScript (e.g. `colorPicker.color.hexString = "#000"`)? Should it force the color's V channel to be 100%?

Sorry for the slow response, by the way. :>

**Comment by Ape** [comment]
No, I don't want to hide the brightness slider. I still want to have it affect the actual output color value just as it does now.

The only think I want is to always render the wheel pretending the slider is at max brightness.

The behaviour and output values should remaing unchanged. This would change how the colors in the wheel are drawn.

**Comment by jaames** [comment]
Ah I see, sorry for the confusion.

To be honest I'm hesitant to add this, I feel that this would be counter-intuitive for the user since the intention was for the middle of both control markers to be over the currently selected color at all times.

That said, if you wanted to, you could perhaps fork the library and change [this line](https://github.com/jaames/iro.js/blob/master/src/ui/wheel.js#L66) so that `value` = 100 permanently. Or if you're willing to wait, the new SVG-based UI being worked on in svg-ui branch will be much more flexible and will allow you to do what you want with just a line of CSS.

**Comment by replicat0r** [comment]
I think having the option to disable the brightness slider makes a lot of sense. What you proposed

valueSlider: false

as a part of the init setting makes a lot of sense!
