### ISSUE TITLE
Change the handle position without firing an event

### ISSUE THREAD

**Issue by hexxter** [jaames/iro.js#97]
is it necessary to set the position of the button to an other location (color value)  without fire a event.
In my case i have multiple browser and send to each of it the RGB value via mqtt. If i slide to an color value i will transfer it to the other clients and set the button to the new color position.

Thx Hexxter

**Comment by jaames** [comment]
Sorry, I'm kinda struggling to understand what you're asking.

It sounds like you might want to use the `input:change` event instead of the `color:change` event. The difference is that `input:change` only fires when the color has been changed *with user input*, while `color:change` fires *whenever* the color is changed.

Here's some example code:

```js
var colorPicker = new iro.ColorPicker({
   color: '#fff',
});

colorPicker.on('input:change', function(color) {
  // send color to other clients
});

// whenever the color is changed by another client
colorPicker.color.rgb = newRgbValueFromOtherClient
```
